# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger: none

pool:
  name: "Daknis"

steps:
# Config
- task: ms-secdevops-test.vss-secure-development-tools-test.build-task-guardian.Guardian@1
  inputs:
    config: '$(Build.SourcesDirectory)\codesign.gdnconfig'
# Default policy
- task: ms-secdevops-test.vss-secure-development-tools-test.build-task-guardian.Guardian@1
# Policy
- task: ms-secdevops-test.vss-secure-development-tools-test.build-task-guardian.Guardian@1
  inputs:
    policy: 'microsoft'
- task: ms-secdevops-test.vss-secure-development-tools-test.build-task-guardian.Guardian@1
# Policy
- task: ms-secdevops-test.vss-secure-development-tools-test.build-task-guardian.Guardian@1
  inputs:
    policy: 'microsoft'
    break: true