# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  default:
    - parallel:
      - step:
          name: 'MSDO trivy test'
          script:
            - unzip ./linux-x64.zip
            - chmod +x linux-x64/guardian
            - chmod +x linux-x64/Microsoft.Guardian.Cli
            - ls -lah .
            - linux-x64/guardian init --force
            - linux-x64/guardian run -t trivy --export-file ./ubuntu-test.sarif --publish-file-folder-path ./ubuntu-test.sarif
